import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Samael',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Tati',
      email: 'tati@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Calça Caqui',
      slug: 'calca-caqui',
      category: 'Calças',
      image: '/images/calca1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Uma calça popular',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Calça Cargo',
      slug: 'calca-cargo',
      category: 'Calças',
      image: '/images/calca2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Uma calça popular',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Calça Offwhite',
      slug: 'calca-offwhite',
      category: 'Calças',
      image: '/images/calca3.png',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Uma calça popular',
    },
    {
      name: 'Cropped Ombro',
      slug: 'cropped-ombro',
      category: 'Croppeds',
      image: '/images/cropped1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Cropped com aparência elegante',
    },
    {
      name: 'cropped Branco',
      slug: 'cropped-branco',
      category: 'Croppeds',
      image: '/images/cropped2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Cropped populares',
    },
    {
      name: 'Cropped Black',
      slug: 'cropped-black',
      category: 'Croppeds',
      image: '/images/cropped3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Cropped populares',
    },
  ],
}
export default data
